// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using micromarket.Config;

#nullable disable

namespace micromarket.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20231114000846_seedcrazy")]
    partial class seedcrazy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_roletouser", b =>
                {
                    b.Property<string>("A")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("B")
                        .HasColumnType("varchar(255)");

                    b.HasKey("A", "B");

                    b.HasIndex("B");

                    b.ToTable("_roletouser");
                });

            modelBuilder.Entity("micromarket.Models.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("padre_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prefijo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("padre_id");

                    b.ToTable("categoria");

                    b.HasData(
                        new
                        {
                            id = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            nombre = "Alimento bebible de Soya",
                            prefijo = "01"
                        },
                        new
                        {
                            id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            nombre = "Bebidas",
                            prefijo = "02"
                        },
                        new
                        {
                            id = "160d1544-5256-445a-9b82-17ba620fc157",
                            nombre = "Agua",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "21"
                        },
                        new
                        {
                            id = "968c060a-d5d4-4d3c-997f-80821d65f022",
                            nombre = "Bebida refrescante",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "22"
                        },
                        new
                        {
                            id = "984709a0-79f0-4825-9242-940cdeec6f92",
                            nombre = "Juguito",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "23"
                        },
                        new
                        {
                            id = "9cf7e664-68e5-424f-9dc1-de4780e2c789",
                            nombre = "Frutts tetra",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "24"
                        },
                        new
                        {
                            id = "b377cf12-b224-469e-8898-074c1e08fc6c",
                            nombre = "Cafe",
                            prefijo = "03"
                        },
                        new
                        {
                            id = "ab9a9c37-31de-47ee-89a5-1e0921220438",
                            nombre = "Congelados",
                            prefijo = "04"
                        },
                        new
                        {
                            id = "3d4901fc-71f4-4586-9bd3-a77d2a71c814",
                            nombre = "Conservas de frutas",
                            prefijo = "05"
                        },
                        new
                        {
                            id = "fc60f291-c024-48e6-ba0b-ae14272d8d70",
                            nombre = "Crema respostera",
                            prefijo = "06"
                        },
                        new
                        {
                            id = "e415d736-eaee-4563-93d6-052f22b7305e",
                            nombre = "Dulce de leche",
                            prefijo = "07"
                        },
                        new
                        {
                            id = "744fa27c-41c6-4337-b968-90b5677c3711",
                            nombre = "Fideos",
                            prefijo = "08"
                        },
                        new
                        {
                            id = "e64b0949-a59f-4309-85a1-b08bcfe80196",
                            nombre = "Leche de condensada",
                            prefijo = "09"
                        },
                        new
                        {
                            id = "d82b11f5-2ac7-44c1-af01-da95afb72ab5",
                            nombre = "Leches Fluidas",
                            prefijo = "10"
                        },
                        new
                        {
                            id = "e9845636-3ce3-43f8-9d80-002a83a7d105",
                            nombre = "Lomitos de atun",
                            prefijo = "11"
                        },
                        new
                        {
                            id = "fb648f85-1dfc-434e-93ed-9f8d84a0967d",
                            nombre = "Mantequilla",
                            prefijo = "12"
                        },
                        new
                        {
                            id = "27ddffa1-46cd-4ffa-b256-d5f31af645df",
                            nombre = "Margarina",
                            prefijo = "13"
                        },
                        new
                        {
                            id = "50c686ed-915e-4edb-acc4-4cc3ba11fa84",
                            nombre = "Mermelada",
                            prefijo = "14"
                        },
                        new
                        {
                            id = "5365364f-784d-4ae3-ba10-02b1da5aea66",
                            nombre = "Panetones",
                            prefijo = "15"
                        });
                });

            modelBuilder.Entity("micromarket.Models.Product", b =>
                {
                    b.Property<string>("codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("categoriaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("descripción")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("imagenURL")
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("precio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("codigo");

                    b.HasIndex("categoriaId");

                    b.ToTable("producto");

                    b.HasData(
                        new
                        {
                            codigo = "DNT-01-0001",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2F3-300x300.png?alt=media&token=6ee2d102-1c75-4e03-95b5-68ad7437e789",
                            nombre = "Soy banana bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0002",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-choco-300x300.jpg?alt=media&token=15621d77-fede-4aa0-84b8-183e102f5cba",
                            nombre = "Soy chocolate bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0003",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2F4-300x300.png?alt=media&token=4d342099-aea0-48d8-a970-4390c6d330c2",
                            nombre = "Soy frutilla bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0004",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-original-300x300.jpg?alt=media&token=d9d1ec8a-c617-4091-896f-92d621c2408d",
                            nombre = "Soy natural bolsa 1.100 MLL",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0005",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-chirimoya-300x300.jpg?alt=media&token=4810853d-8855-4448-8a2d-36e9533b2e06",
                            nombre = "Soy chirimoya bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0006",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-vainilla-300x300.jpg?alt=media&token=adfae0b2-3cbd-4b3c-aea1-359d26ba400e",
                            nombre = "Soy vainilla bolsa 1.100 ML",
                            precio = "9.99"
                        });
                });

            modelBuilder.Entity("micromarket.Models.Role", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("micromarket.Models.User", b =>
                {
                    b.Property<string>("nombre_de_usuario")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contraseña")
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .HasColumnType("longtext");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("nombre_de_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("_roletouser", b =>
                {
                    b.HasOne("micromarket.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("A")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("micromarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("B")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("micromarket.Models.Category", b =>
                {
                    b.HasOne("micromarket.Models.Category", "padre")
                        .WithMany("categorias")
                        .HasForeignKey("padre_id");

                    b.Navigation("padre");
                });

            modelBuilder.Entity("micromarket.Models.Product", b =>
                {
                    b.HasOne("micromarket.Models.Category", "categoria")
                        .WithMany("productos")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("micromarket.Models.Category", b =>
                {
                    b.Navigation("categorias");

                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
