// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using micromarket.Config;

#nullable disable

namespace micromarket.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20231110130208_checkdb")]
    partial class checkdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_roletouser", b =>
                {
                    b.Property<string>("A")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("B")
                        .HasColumnType("varchar(255)");

                    b.HasKey("A", "B");

                    b.HasIndex("B");

                    b.ToTable("_roletouser");
                });

            modelBuilder.Entity("micromarket.Models.Role", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("micromarket.Models.User", b =>
                {
                    b.Property<string>("nombre_de_usuario")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("nombre_de_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("_roletouser", b =>
                {
                    b.HasOne("micromarket.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("A")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("micromarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("B")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
