// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using micromarket.Config;

#nullable disable

namespace micromarket.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20231113203729_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_roletouser", b =>
                {
                    b.Property<string>("A")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("B")
                        .HasColumnType("varchar(255)");

                    b.HasKey("A", "B");

                    b.HasIndex("B");

                    b.ToTable("_roletouser");
                });

            modelBuilder.Entity("micromarket.Models.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("padre_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prefijo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("padre_id");

                    b.ToTable("categoria");

                    b.HasData(
                        new
                        {
                            id = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            nombre = "Alimento bebible de Soya",
                            prefijo = "01"
                        },
                        new
                        {
                            id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            nombre = "Bebidas",
                            prefijo = "02"
                        },
                        new
                        {
                            id = "160d1544-5256-445a-9b82-17ba620fc157",
                            nombre = "Agua",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "21"
                        },
                        new
                        {
                            id = "968c060a-d5d4-4d3c-997f-80821d65f022",
                            nombre = "Bebida refrescante",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "22"
                        },
                        new
                        {
                            id = "984709a0-79f0-4825-9242-940cdeec6f92",
                            nombre = "Juguito",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "23"
                        },
                        new
                        {
                            id = "9cf7e664-68e5-424f-9dc1-de4780e2c789",
                            nombre = "Frutts tetra",
                            padre_id = "20368c37-79ab-4bde-aca2-1ff189012374",
                            prefijo = "24"
                        });
                });

            modelBuilder.Entity("micromarket.Models.Product", b =>
                {
                    b.Property<string>("codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("categoriaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("descripción")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("imagenURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("precio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("codigo");

                    b.HasIndex("categoriaId");

                    b.ToTable("producto");

                    b.HasData(
                        new
                        {
                            codigo = "DNT-01-0001",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2F3-300x300.png?alt=media&token=6ee2d102-1c75-4e03-95b5-68ad7437e789",
                            nombre = "Soy banana bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0002",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-choco-300x300.jpg?alt=media&token=15621d77-fede-4aa0-84b8-183e102f5cba",
                            nombre = "Soy chocolate bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0003",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2F4-300x300.png?alt=media&token=4d342099-aea0-48d8-a970-4390c6d330c2",
                            nombre = "Soy frutilla bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0004",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-original-300x300.jpg?alt=media&token=d9d1ec8a-c617-4091-896f-92d621c2408d",
                            nombre = "Soy natural bolsa 1.100 MLL",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0005",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-chirimoya-300x300.jpg?alt=media&token=4810853d-8855-4448-8a2d-36e9533b2e06",
                            nombre = "Soy chirimoya bolsa 1.100 ML",
                            precio = "9.99"
                        },
                        new
                        {
                            codigo = "DNT-01-0006",
                            categoriaId = "1862b90e-034c-4ce2-9e26-0d3c8ce875e9",
                            descripción = "El alimento bebible de soya no contiene lactosa",
                            imagenURL = "https://firebasestorage.googleapis.com/v0/b/micromarket-35ab5.appspot.com/o/productos%2Fcategorias%2Falimento%20soya%20bebible%2Fsoy-vainilla-300x300.jpg?alt=media&token=adfae0b2-3cbd-4b3c-aea1-359d26ba400e",
                            nombre = "Soy vainilla bolsa 1.100 ML",
                            precio = "9.99"
                        });
                });

            modelBuilder.Entity("micromarket.Models.Role", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("micromarket.Models.User", b =>
                {
                    b.Property<string>("nombre_de_usuario")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contraseña")
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .HasColumnType("longtext");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("nombre_de_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("_roletouser", b =>
                {
                    b.HasOne("micromarket.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("A")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("micromarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("B")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("micromarket.Models.Category", b =>
                {
                    b.HasOne("micromarket.Models.Category", "padre")
                        .WithMany("categorias")
                        .HasForeignKey("padre_id");

                    b.Navigation("padre");
                });

            modelBuilder.Entity("micromarket.Models.Product", b =>
                {
                    b.HasOne("micromarket.Models.Category", "categoria")
                        .WithMany("productos")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("micromarket.Models.Category", b =>
                {
                    b.Navigation("categorias");

                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
